"""Catálogo ISO 3166-1 alfa-2 (249 países/territorios) con continente.

Se usa para el selector de Origen (ISO-2) filtrado por continente y como maestro
de países para acuerdos/preferencias. `seed_countries` hace upsert por iso2:
inserta los que faltan y completa continente/iso3 en los existentes.
"""
from __future__ import annotations

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.trade import Country

# (iso2, iso3, nombre_es, continente)
COUNTRIES: list[tuple[str, str, str, str]] = [
    # ---------------- América ----------------
    ("AG", "ATG", "Antigua y Barbuda", "América"),
    ("AI", "AIA", "Anguila", "América"),
    ("AR", "ARG", "Argentina", "América"),
    ("AW", "ABW", "Aruba", "América"),
    ("BB", "BRB", "Barbados", "América"),
    ("BL", "BLM", "San Bartolomé", "América"),
    ("BM", "BMU", "Bermudas", "América"),
    ("BO", "BOL", "Bolivia", "América"),
    ("BQ", "BES", "Bonaire, San Eustaquio y Saba", "América"),
    ("BR", "BRA", "Brasil", "América"),
    ("BS", "BHS", "Bahamas", "América"),
    ("BZ", "BLZ", "Belice", "América"),
    ("CA", "CAN", "Canadá", "América"),
    ("CL", "CHL", "Chile", "América"),
    ("CO", "COL", "Colombia", "América"),
    ("CR", "CRI", "Costa Rica", "América"),
    ("CU", "CUB", "Cuba", "América"),
    ("CW", "CUW", "Curazao", "América"),
    ("DM", "DMA", "Dominica", "América"),
    ("DO", "DOM", "República Dominicana", "América"),
    ("EC", "ECU", "Ecuador", "América"),
    ("FK", "FLK", "Islas Malvinas", "América"),
    ("GD", "GRD", "Granada", "América"),
    ("GF", "GUF", "Guayana Francesa", "América"),
    ("GL", "GRL", "Groenlandia", "América"),
    ("GP", "GLP", "Guadalupe", "América"),
    ("GT", "GTM", "Guatemala", "América"),
    ("GY", "GUY", "Guyana", "América"),
    ("HN", "HND", "Honduras", "América"),
    ("HT", "HTI", "Haití", "América"),
    ("JM", "JAM", "Jamaica", "América"),
    ("KN", "KNA", "San Cristóbal y Nieves", "América"),
    ("KY", "CYM", "Islas Caimán", "América"),
    ("LC", "LCA", "Santa Lucía", "América"),
    ("MF", "MAF", "San Martín (parte francesa)", "América"),
    ("MQ", "MTQ", "Martinica", "América"),
    ("MS", "MSR", "Montserrat", "América"),
    ("MX", "MEX", "México", "América"),
    ("NI", "NIC", "Nicaragua", "América"),
    ("PA", "PAN", "Panamá", "América"),
    ("PE", "PER", "Perú", "América"),
    ("PM", "SPM", "San Pedro y Miquelón", "América"),
    ("PR", "PRI", "Puerto Rico", "América"),
    ("PY", "PRY", "Paraguay", "América"),
    ("SR", "SUR", "Surinam", "América"),
    ("SV", "SLV", "El Salvador", "América"),
    ("SX", "SXM", "Sint Maarten (parte neerlandesa)", "América"),
    ("TC", "TCA", "Islas Turcas y Caicos", "América"),
    ("TT", "TTO", "Trinidad y Tobago", "América"),
    ("US", "USA", "Estados Unidos", "América"),
    ("UY", "URY", "Uruguay", "América"),
    ("VC", "VCT", "San Vicente y las Granadinas", "América"),
    ("VE", "VEN", "Venezuela", "América"),
    ("VG", "VGB", "Islas Vírgenes Británicas", "América"),
    ("VI", "VIR", "Islas Vírgenes de EE. UU.", "América"),
    # ---------------- Europa ----------------
    ("AD", "AND", "Andorra", "Europa"),
    ("AL", "ALB", "Albania", "Europa"),
    ("AT", "AUT", "Austria", "Europa"),
    ("AX", "ALA", "Islas Åland", "Europa"),
    ("BA", "BIH", "Bosnia y Herzegovina", "Europa"),
    ("BE", "BEL", "Bélgica", "Europa"),
    ("BG", "BGR", "Bulgaria", "Europa"),
    ("BY", "BLR", "Bielorrusia", "Europa"),
    ("CH", "CHE", "Suiza", "Europa"),
    ("CY", "CYP", "Chipre", "Europa"),
    ("CZ", "CZE", "Chequia", "Europa"),
    ("DE", "DEU", "Alemania", "Europa"),
    ("DK", "DNK", "Dinamarca", "Europa"),
    ("EE", "EST", "Estonia", "Europa"),
    ("ES", "ESP", "España", "Europa"),
    ("FI", "FIN", "Finlandia", "Europa"),
    ("FO", "FRO", "Islas Feroe", "Europa"),
    ("FR", "FRA", "Francia", "Europa"),
    ("GB", "GBR", "Reino Unido", "Europa"),
    ("GG", "GGY", "Guernsey", "Europa"),
    ("GI", "GIB", "Gibraltar", "Europa"),
    ("GR", "GRC", "Grecia", "Europa"),
    ("HR", "HRV", "Croacia", "Europa"),
    ("HU", "HUN", "Hungría", "Europa"),
    ("IE", "IRL", "Irlanda", "Europa"),
    ("IM", "IMN", "Isla de Man", "Europa"),
    ("IS", "ISL", "Islandia", "Europa"),
    ("IT", "ITA", "Italia", "Europa"),
    ("JE", "JEY", "Jersey", "Europa"),
    ("LI", "LIE", "Liechtenstein", "Europa"),
    ("LT", "LTU", "Lituania", "Europa"),
    ("LU", "LUX", "Luxemburgo", "Europa"),
    ("LV", "LVA", "Letonia", "Europa"),
    ("MC", "MCO", "Mónaco", "Europa"),
    ("MD", "MDA", "Moldavia", "Europa"),
    ("ME", "MNE", "Montenegro", "Europa"),
    ("MK", "MKD", "Macedonia del Norte", "Europa"),
    ("MT", "MLT", "Malta", "Europa"),
    ("NL", "NLD", "Países Bajos", "Europa"),
    ("NO", "NOR", "Noruega", "Europa"),
    ("PL", "POL", "Polonia", "Europa"),
    ("PT", "PRT", "Portugal", "Europa"),
    ("RO", "ROU", "Rumanía", "Europa"),
    ("RS", "SRB", "Serbia", "Europa"),
    ("RU", "RUS", "Rusia", "Europa"),
    ("SE", "SWE", "Suecia", "Europa"),
    ("SI", "SVN", "Eslovenia", "Europa"),
    ("SJ", "SJM", "Svalbard y Jan Mayen", "Europa"),
    ("SK", "SVK", "Eslovaquia", "Europa"),
    ("SM", "SMR", "San Marino", "Europa"),
    ("UA", "UKR", "Ucrania", "Europa"),
    ("VA", "VAT", "Ciudad del Vaticano", "Europa"),
    # ---------------- África ----------------
    ("AO", "AGO", "Angola", "África"),
    ("BF", "BFA", "Burkina Faso", "África"),
    ("BI", "BDI", "Burundi", "África"),
    ("BJ", "BEN", "Benín", "África"),
    ("BW", "BWA", "Botsuana", "África"),
    ("CD", "COD", "Rep. Democrática del Congo", "África"),
    ("CF", "CAF", "República Centroafricana", "África"),
    ("CG", "COG", "Congo", "África"),
    ("CI", "CIV", "Costa de Marfil", "África"),
    ("CM", "CMR", "Camerún", "África"),
    ("CV", "CPV", "Cabo Verde", "África"),
    ("DJ", "DJI", "Yibuti", "África"),
    ("DZ", "DZA", "Argelia", "África"),
    ("EG", "EGY", "Egipto", "África"),
    ("EH", "ESH", "Sahara Occidental", "África"),
    ("ER", "ERI", "Eritrea", "África"),
    ("ET", "ETH", "Etiopía", "África"),
    ("GA", "GAB", "Gabón", "África"),
    ("GH", "GHA", "Ghana", "África"),
    ("GM", "GMB", "Gambia", "África"),
    ("GN", "GIN", "Guinea", "África"),
    ("GQ", "GNQ", "Guinea Ecuatorial", "África"),
    ("GW", "GNB", "Guinea-Bisáu", "África"),
    ("KE", "KEN", "Kenia", "África"),
    ("KM", "COM", "Comoras", "África"),
    ("LR", "LBR", "Liberia", "África"),
    ("LS", "LSO", "Lesoto", "África"),
    ("LY", "LBY", "Libia", "África"),
    ("MA", "MAR", "Marruecos", "África"),
    ("MG", "MDG", "Madagascar", "África"),
    ("ML", "MLI", "Malí", "África"),
    ("MR", "MRT", "Mauritania", "África"),
    ("MU", "MUS", "Mauricio", "África"),
    ("MW", "MWI", "Malaui", "África"),
    ("MZ", "MOZ", "Mozambique", "África"),
    ("NA", "NAM", "Namibia", "África"),
    ("NE", "NER", "Níger", "África"),
    ("NG", "NGA", "Nigeria", "África"),
    ("RE", "REU", "Reunión", "África"),
    ("RW", "RWA", "Ruanda", "África"),
    ("SC", "SYC", "Seychelles", "África"),
    ("SD", "SDN", "Sudán", "África"),
    ("SH", "SHN", "Santa Elena", "África"),
    ("SL", "SLE", "Sierra Leona", "África"),
    ("SN", "SEN", "Senegal", "África"),
    ("SO", "SOM", "Somalia", "África"),
    ("SS", "SSD", "Sudán del Sur", "África"),
    ("ST", "STP", "Santo Tomé y Príncipe", "África"),
    ("SZ", "SWZ", "Esuatini", "África"),
    ("TD", "TCD", "Chad", "África"),
    ("TG", "TGO", "Togo", "África"),
    ("TN", "TUN", "Túnez", "África"),
    ("TZ", "TZA", "Tanzania", "África"),
    ("UG", "UGA", "Uganda", "África"),
    ("YT", "MYT", "Mayotte", "África"),
    ("ZA", "ZAF", "Sudáfrica", "África"),
    ("ZM", "ZMB", "Zambia", "África"),
    ("ZW", "ZWE", "Zimbabue", "África"),
    # ---------------- Asia ----------------
    ("AE", "ARE", "Emiratos Árabes Unidos", "Asia"),
    ("AF", "AFG", "Afganistán", "Asia"),
    ("AM", "ARM", "Armenia", "Asia"),
    ("AZ", "AZE", "Azerbaiyán", "Asia"),
    ("BD", "BGD", "Bangladés", "Asia"),
    ("BH", "BHR", "Baréin", "Asia"),
    ("BN", "BRN", "Brunéi", "Asia"),
    ("BT", "BTN", "Bután", "Asia"),
    ("CC", "CCK", "Islas Cocos", "Asia"),
    ("CN", "CHN", "China", "Asia"),
    ("CX", "CXR", "Isla de Navidad", "Asia"),
    ("GE", "GEO", "Georgia", "Asia"),
    ("HK", "HKG", "Hong Kong", "Asia"),
    ("ID", "IDN", "Indonesia", "Asia"),
    ("IL", "ISR", "Israel", "Asia"),
    ("IN", "IND", "India", "Asia"),
    ("IO", "IOT", "Territorio Británico del Océano Índico", "Asia"),
    ("IQ", "IRQ", "Irak", "Asia"),
    ("IR", "IRN", "Irán", "Asia"),
    ("JO", "JOR", "Jordania", "Asia"),
    ("JP", "JPN", "Japón", "Asia"),
    ("KG", "KGZ", "Kirguistán", "Asia"),
    ("KH", "KHM", "Camboya", "Asia"),
    ("KP", "PRK", "Corea del Norte", "Asia"),
    ("KR", "KOR", "Corea del Sur", "Asia"),
    ("KW", "KWT", "Kuwait", "Asia"),
    ("KZ", "KAZ", "Kazajistán", "Asia"),
    ("LA", "LAO", "Laos", "Asia"),
    ("LB", "LBN", "Líbano", "Asia"),
    ("LK", "LKA", "Sri Lanka", "Asia"),
    ("MM", "MMR", "Myanmar", "Asia"),
    ("MN", "MNG", "Mongolia", "Asia"),
    ("MO", "MAC", "Macao", "Asia"),
    ("MV", "MDV", "Maldivas", "Asia"),
    ("MY", "MYS", "Malasia", "Asia"),
    ("NP", "NPL", "Nepal", "Asia"),
    ("OM", "OMN", "Omán", "Asia"),
    ("PH", "PHL", "Filipinas", "Asia"),
    ("PK", "PAK", "Pakistán", "Asia"),
    ("PS", "PSE", "Palestina", "Asia"),
    ("QA", "QAT", "Catar", "Asia"),
    ("SA", "SAU", "Arabia Saudita", "Asia"),
    ("SG", "SGP", "Singapur", "Asia"),
    ("SY", "SYR", "Siria", "Asia"),
    ("TH", "THA", "Tailandia", "Asia"),
    ("TJ", "TJK", "Tayikistán", "Asia"),
    ("TL", "TLS", "Timor Oriental", "Asia"),
    ("TM", "TKM", "Turkmenistán", "Asia"),
    ("TR", "TUR", "Turquía", "Asia"),
    ("TW", "TWN", "Taiwán", "Asia"),
    ("UZ", "UZB", "Uzbekistán", "Asia"),
    ("VN", "VNM", "Vietnam", "Asia"),
    ("YE", "YEM", "Yemen", "Asia"),
    # ---------------- Oceanía ----------------
    ("AS", "ASM", "Samoa Americana", "Oceanía"),
    ("AU", "AUS", "Australia", "Oceanía"),
    ("CK", "COK", "Islas Cook", "Oceanía"),
    ("FJ", "FJI", "Fiyi", "Oceanía"),
    ("FM", "FSM", "Micronesia", "Oceanía"),
    ("GU", "GUM", "Guam", "Oceanía"),
    ("KI", "KIR", "Kiribati", "Oceanía"),
    ("MH", "MHL", "Islas Marshall", "Oceanía"),
    ("MP", "MNP", "Islas Marianas del Norte", "Oceanía"),
    ("NC", "NCL", "Nueva Caledonia", "Oceanía"),
    ("NF", "NFK", "Isla Norfolk", "Oceanía"),
    ("NR", "NRU", "Nauru", "Oceanía"),
    ("NU", "NIU", "Niue", "Oceanía"),
    ("NZ", "NZL", "Nueva Zelanda", "Oceanía"),
    ("PF", "PYF", "Polinesia Francesa", "Oceanía"),
    ("PG", "PNG", "Papúa Nueva Guinea", "Oceanía"),
    ("PN", "PCN", "Islas Pitcairn", "Oceanía"),
    ("PW", "PLW", "Palaos", "Oceanía"),
    ("SB", "SLB", "Islas Salomón", "Oceanía"),
    ("TK", "TKL", "Tokelau", "Oceanía"),
    ("TO", "TON", "Tonga", "Oceanía"),
    ("TV", "TUV", "Tuvalu", "Oceanía"),
    ("UM", "UMI", "Islas menores alejadas de EE. UU.", "Oceanía"),
    ("VU", "VUT", "Vanuatu", "Oceanía"),
    ("WF", "WLF", "Wallis y Futuna", "Oceanía"),
    ("WS", "WSM", "Samoa", "Oceanía"),
    # ---------------- Antártida ----------------
    ("AQ", "ATA", "Antártida", "Antártida"),
    ("BV", "BVT", "Isla Bouvet", "Antártida"),
    ("GS", "SGS", "Georgia del Sur e Islas Sandwich del Sur", "Antártida"),
    ("HM", "HMD", "Islas Heard y McDonald", "Antártida"),
    ("TF", "ATF", "Territorios Australes Franceses", "Antártida"),
]


async def seed_countries(session: AsyncSession) -> dict:
    """Upsert del catálogo ISO. Inserta faltantes; completa continente/iso3 en los
    existentes (sin pisar el nombre ya cargado)."""
    existing = {c.iso2: c for c in (await session.scalars(select(Country))).all()}
    created = 0
    updated = 0
    for iso2, iso3, name, continent in COUNTRIES:
        cur = existing.get(iso2)
        if cur is None:
            session.add(Country(iso2=iso2, iso3=iso3, name=name, continent=continent, active=True))
            created += 1
        else:
            changed = False
            if not cur.continent:
                cur.continent = continent
                changed = True
            if not cur.iso3:
                cur.iso3 = iso3
                changed = True
            if changed:
                updated += 1
    await session.flush()
    return {"created": created, "updated": updated, "total": len(COUNTRIES)}
